### ISSUE TITLE
Crash after login.

### ISSUE THREAD

**Issue by ElecTwix** [EnyoYoen/Fast-Discord#14]
Crash After Login
Log
`Floating point exception (core dumped)`

Downloaded via [AUR Package](https://aur.archlinux.org/packages/fast-discord-git)

**Comment by EnyoYoen** [comment]
I installed Fast-Discord in an Arch Linux VM via AUR and it worked, are you using Qt 5.15 and did you enter the correct token? Or can you run Fast-Discord with gdb and print the backtrace when it crashes?

**Comment by ElecTwix** [comment]
yes, I tripled and checked the token it is correct but when I build from the source it is working I think something wrong with the AUR package.

**Comment by EnyoYoen** [comment]
This may have been fixed in last push, if not, can you print the backtrace when it crashes with gdb? That would be really useful.

**Comment by ElecTwix** [comment]
Log
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff29296c0 (LWP 30722)]
[New Thread 0x7ffff20996c0 (LWP 30723)]
[New Thread 0x7ffff11a96c0 (LWP 30724)]
[New Thread 0x7ffff09a86c0 (LWP 30725)]
[New Thread 0x7fffea5ff6c0 (LWP 30726)]
[New Thread 0x7fffe9dfe6c0 (LWP 30727)]
[New Thread 0x7fffe95fd6c0 (LWP 30728)]
[New Thread 0x7fffe8dfc6c0 (LWP 30729)]
[New Thread 0x7fffdcdff6c0 (LWP 30730)]
[New Thread 0x7fffbffff6c0 (LWP 30731)]
[New Thread 0x7fffbf7fe6c0 (LWP 30732)]
[New Thread 0x7fffbeffd6c0 (LWP 30733)]
[New Thread 0x7fffbe7fc6c0 (LWP 30734)]
[New Thread 0x7fffbdffb6c0 (LWP 30735)]
[New Thread 0x7fffbd7fa6c0 (LWP 30736)]
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 444, resource id: 4208246, major code: 40 (TranslateCoords), minor code: 0
[New Thread 0x7fffbcff96c0 (LWP 30737)]


///------------------///

(gdb) backtrace

#0  0x000055555565c4c8 in ?? ()
#1  0x00005555555f9487 in Api::RessourceManager::getImage(std::function<void (void*)>, QString const&, QString const&) ()
#2  0x000055555565fd5a in ?? ()
#3  0x00005555555f8288 in ?? ()
#4  0x00005555555eefdc in Api::Requester::callCallbacks(Api::RequestParametersNoCb const&, void*) ()
#5  0x00005555555f1406 in Api::Requester::readReply() ()
#6  0x00007ffff6abe0d1 in ?? () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff6f316d8 in ?? () from /usr/lib/libQt5Network.so.5
#8  0x00007ffff6ab12f0 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff7978b3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff6a8d978 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff6a8e483 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff6ad4478 in ?? () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff5b91c6b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff5be8001 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007ffff5b8f392 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff6ad825c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff6a8611c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff6a90c49 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#19 0x00005555555b8c07 in main ()

Thread 1 "fast-discord" received signal SIGFPE, Arithmetic exception.
```
